//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedidoresDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direccion
    {
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Numero { get; set; }
        public string CodigoRegion { get; set; }
        public string CodigoCliente { get; set; }
        public int IdMedidor { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Medidor Medidor { get; set; }
        public virtual Region Region { get; set; }
    }
}
