//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedidoresDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedidoresDBEntities : DbContext
    {
        public MedidoresDBEntities()
            : base("name=MedidoresDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Direccion> Direccion { get; set; }
        public virtual DbSet<Medicion> Medicion { get; set; }
        public virtual DbSet<Medidor> Medidor { get; set; }
        public virtual DbSet<Region> Region { get; set; }
        public virtual DbSet<TarifaElectrica> TarifaElectrica { get; set; }
        public virtual DbSet<Trabajador> Trabajador { get; set; }
    }
}
